# Generated by Django 3.0.5 on 2023-08-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_result_total_mark_result_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='questions',
        ),
        migrations.AddField(
            model_name='result',
            name='total_marks',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
